version: "3.9"
services:
  db:
    image: "postgres:latest"
    ports:
      - "5430:5432"
    volumes:
      - app_thingo:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  app_thingo:



