"""initial

Revision ID: 06f05e67dcf8
Revises: 
Create Date: 2021-12-24 11:45:36.686936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f05e67dcf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_person',
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_names', sa.String(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index(op.f('ix_crm_person_person_id'), 'crm_person', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_person_person_id'), table_name='crm_person')
    op.drop_table('crm_person')
    # ### end Alembic commands ###
